# Generated by Django 5.0.4 on 2026-05-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_bookmark_type_alter_bookmark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('company', 'Company'), ('question', 'Question'), ('resource', 'Resource')], max_length=10),
        ),
    ]
