# Generated by Django 5.2.6 on 2026-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
