# Generated by Django 5.0.4 on 2026-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecom'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('crew', 'Crew'), ('admin', 'Admin')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Final')], null=True),
        ),
    ]
