# Generated by Django 5.0.4 on 2026-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecom'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('CyberSecurity', 'CyberSecurity'), ('MBA', 'MBA'), ('Other', 'Other')], max_length=20),
        ),
    ]
