# Generated by Django 5.0.4 on 2026-05-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(upload_to='campus_sarthi/study_materials/'),
        ),
    ]
