# Generated by Django 5.0.4 on 2026-05-03 09:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_materials', '0002_remove_studymaterial_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='campus_sarthi/study_materials/'),
        ),
    ]
