# Generated by Django 5.0.4 on 2026-06-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
