# Generated by Django 5.2.6 on 2026-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_category_alter_resource_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
