# Generated by Django 5.0.4 on 2026-06-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('Video', 'Video'), ('Notes', 'Notes'), ('Practice Set', 'Practice Set'), ('Roadmap', 'Roadmap')], default='Notes', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('CyberSecurity', 'Cyber Security'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('DataScience', 'Data Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication Engineering'), ('EE', 'Electrical Engineering'), ('Mechanical', 'Mechanical Engineering'), ('Civil', 'Civil Engineering'), ('MBA', 'MBA / Management'), ('Pharmacy', 'Pharmacy'), ('Aptitude', 'Aptitude Preparation'), ('Communication', 'Communication Skills'), ('Placement', 'Placement Preparation'), ('HigherStudies', 'Higher Studies (GATE/GRE/CAT)')], max_length=50),
        ),
    ]
