# Generated by Django 5.0.4 on 2026-04-26 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crewrating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
