# Generated by Django 5.0.4 on 2026-05-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crewmember_created_at_alter_crewmember_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Faculty', 'Faculty'), ('Mentor', 'Mentor'), ('Crew', 'Crew'), ('Lead', 'Lead')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campus_sarthi/placement_family/')),
                ('hierarchy_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
    ]
