# Generated by Django 5.0.4 on 2026-04-26 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('domain', models.CharField(choices=[('CS', 'CS'), ('Cyber', 'Cyber'), ('Product', 'Product'), ('Sales', 'Sales')], max_length=20)),
                ('about', models.TextField()),
                ('job_role', models.CharField(max_length=255)),
                ('salary_lpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tech_requirements', models.JSONField(default=list)),
                ('gd_questions', models.JSONField(default=list)),
                ('interview_questions', models.JSONField(default=list)),
                ('eligibility_criteria', models.TextField()),
                ('bond_details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
