# Generated by Django 5.2.6 on 2026-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_bond_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='joining_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='package_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='selection_rounds',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='service_bond',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='tentative_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
